version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: url_minifier
    container_name: url_minifier-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - url_minifier
  mysql:
    image: mysql:8.0.28
    container_name: url_minifier-mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker-data/mysql/db-data:/var/lib/mysql:delegated
    networks:
      - url_minifier
  nginx:
    image: nginx:alpine
    container_name: url_minifier-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-data/nginx:/etc/nginx/conf.d/
    networks:
      - url_minifier
networks:
  url_minifier:
    driver: bridge
